import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
import JokeList from '../components/JokeList'

export default function Home({jokes}) {
  
  return (
    <div className={styles.container}>
      <Head>
        <title>Chuck Norris Jokes</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <main className={styles.main}>
        <h1 className={styles.title}>
            Welcome to Chuck Norris Jokes !
        </h1>
        <br></br><br></br><br></br><br></br>

        <JokeList jokes={jokes}></JokeList>
      </main>
    </div>
  )
}

export async function getStaticProps() {
  const res = await fetch('https://api.chucknorris.io/jokes/categories')
  const jokes = await res.json()
  console.log('hiiiii')

  return{
    props:{
      jokes,
    },
  }
}

